### ISSUE TITLE
Consultas sobre el TP

### ISSUE THREAD

**Issue by ivanfranco502** [PDSDotNet/AspNetCoreTodo2#1]
@PDSDotNet Respondo las consultas realizadas:

> 1. ¿Tendría que haber puesto el anotation [ValidateAntiForgeryToken] antes de los métodos?
**Si los métodos no van a ser overrideados por las clases hijas sí es necesario definir la annotation en la clase padre para evitar que en ambos métodos (TodoController y EndTodoController) se pueda realizar un Cross site request forgery.**

> 2. ¿Tendría que haber puesto el anotation [Authorize] antes de la definición de BaseController?
**Podés agregarlo siempre y cuando los controllers que hereden de BaseController tengan necesariamente la necesidad de ser utilizados con autorización. Si llegas a utilizar el BaseController para una funcionalidad adicional y haces heredar a un controller que no requiere Authorize, estarías modificando el comportamiento (dado que la clase padre lo obliga a estar identificado).**

**Comment by PDSDotNet** [comment]
Muchas gracias Ivan, voy a agregar  [ValidateAntiForgeryToken], y también
voy a agregar  [Authorize] (ya que la idea original era que nadie sin
logear pudiera ver los Todos, despues EL BARBA proveerá)

Saludos
